### ISSUE TITLE
About local dataset

### ISSUE THREAD

**Issue by Manel-Hik** [huggingface/datatrove#109]
Hi
I'm trying to apply the example of sentence deduplication with my own dataset from the CC but it's already extracted and prepared in jsonl format
my question is how should I edit those block of codes 

```
`def run_example():
    pipeline_1 = [
        WarcReader(data_folder="warc/", limit=1000),
        Trafilatura(),
        GopherQualityFilter(min_stop_words=0),
        LanguageFilter(language_threshold=0.5, languages=(Languages.english,)),
        JsonlWriter("intermediate/"),
        SentenceDedupSignature(output_folder="c4/"),
    ]
    pipeline_2 = [
        SentenceFindDedups(
            data_folder="c4/",
            output_folder="c4/",
        )
    ]

```
   ```
 pipeline_3 = [
        JsonlReader(data_folder="intermediate/"),
        SentenceDedupFilter(data_folder="c4/"),
    ]`
```
    Especially in pipeline 1 should it be like this : 
  ```
  `pipeline_1 = [
        JsonlReader("my_data.jsonl"),
        SentenceDedupSignature(output_folder="my_folder/")
    ]

    pipeline_2 = [
        SentenceFindDedups(
            data_folder="my_folder/",
            output_folder="my_folder/"
        )
    ]

    pipeline_3 = [
        JsonlReader(data_folder="my_data.jsonl"),
        SentenceDedupFilter(data_folder="my_folder/")
    ]`
```
    I runned with that modification but I got this error:
    `2024-02-27 09:44:50.328 | INFO     | datatrove.utils.logging:add_task_logger:47 - Launching pipeline for rank=0
2024-02-27 09:44:50.328 | INFO     | datatrove.utils.logging:log_pipeline:76 - 
--- 🛠️ PIPELINE 🛠
📖 - READER: 🐿 Jsonl
🫂 - DEDUPS: 💥 sentence-deduplication stage 1
2024-02-27 09:44:50.328 | INFO     | datatrove.pipeline.readers.base:read_files_shard:160 - Reading input file 
2024-02-27 09:44:50.329 | WARNING  | datatrove.pipeline.readers.base:get_document_from_dict:78 - Found document without text, skipping. Is your `text_key` ("text") correct?
2024-02-27 09:44:50.367 | INFO     | datatrove.executor.local:_launch_run_for_rank:62 - 1/4 tasks completed.
2024-02-27 09:44:50.406 | INFO     | datatrove.executor.local:_launch_run_for_rank:62 - 2/4 tasks completed.
2024-02-27 09:44:50.414 | INFO     | datatrove.executor.local:_launch_run_for_rank:62 - 3/4 tasks completed.
2024-02-27 09:44:51.928 | SUCCESS  | datatrove.executor.base:_run_for_rank:85 - Processing done for rank=0
2024-02-27 09:44:51.929 | INFO     | datatrove.executor.base:_run_for_rank:91 - 

📉📉📉 Stats: Task 0 📉📉📉

Total Runtime: 1 second

📖 - READER: 🐿 Jsonl
    Runtime: (1.16%) 0 seconds [0.04 milliseconds±0.03 milliseconds/doc]
    Stats: {input_files: 1, doc_len: 3002046 [min=30, max=120653, 21375.53±29918/task], documents: 496 [496.00/input_file]}
🫂 - DEDUPS: 💥 sentence-deduplication stage 1
    Runtime: (98.84%) 1 second [3.06 milliseconds±20.05 milliseconds/doc]
    Stats: {total: 497}
2024-02-27 09:44:51.933 | INFO     | datatrove.executor.local:_launch_run_for_rank:62 - 4/4 tasks completed.
2024-02-27 09:44:51.964 | SUCCESS  | datatrove.executor.local:run:114 - 

📉📉📉 Stats: All 4 tasks 📉📉📉

Total Runtime: 0 seconds ± 0 seconds/task

📖 - READER: 🐿 Jsonl
    Runtime: (1.16%) 0 seconds±0 seconds/task, min=0 seconds [0.04 milliseconds±0.03 milliseconds/doc]
    Stats: {input_files: 1, doc_len: 3002046 [min=30, max=120653, 21375.53±29918/task], documents: 496 [496.00/input_file]}
🫂 - DEDUPS: 💥 sentence-deduplication stage 1
    Runtime: (98.84%) 0 seconds±0 seconds/task, min=0 seconds [3.06 milliseconds±20.05 milliseconds/doc]
    Stats: {total: 497}

📉📉📉 Stats 📉📉📉

Total Runtime: 0 seconds ± 0 seconds/task

📖 - READER: 🐿 Jsonl
    Runtime: (1.16%) 0 seconds±0 seconds/task, min=0 seconds [0.04 milliseconds±0.03 milliseconds/doc]
    Stats: {input_files: 1, doc_len: 3002046 [min=30, max=120653, 21375.53±29918/task], documents: 496 [496.00/input_file]}
🫂 - DEDUPS: 💥 sentence-deduplication stage 1
    Runtime: (98.84%) 0 seconds±0 seconds/task, min=0 seconds [3.06 milliseconds±20.05 milliseconds/doc]
    Stats: {total: 497}
2024-02-27 09:44:51.987 | INFO     | datatrove.utils.logging:add_task_logger:47 - Launching pipeline for rank=0
2024-02-27 09:44:51.988 | INFO     | datatrove.utils.logging:log_pipeline:76 - 
--- 🛠️ PIPELINE 🛠
🫂 - DEDUPS: 💥 sentence-deduplication stage 2
2024-02-27 09:44:51.989 | ERROR    | datatrove.executor.base:_run_for_rank:95 - 
Traceback (most recent call last):

  File "/datatrove/examples/sentence_deduplication.py", line 55, in <module>
    run_example()
    └ <function run_example at 0x7f348dd745e0>

  File "/datatrove/examples/sentence_deduplication.py", line 50, in run_example
    print(executor_2.run())
          │          └ <function LocalPipelineExecutor.run at 0x7f348b3f9360>
          └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7f3430c9c6a0>

  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/local.py", line 93, in run
    stats.append(self._launch_run_for_rank(rank, ranks_q))
    │     │      │    │                    │     └ <AutoProxy[Queue] object, typeid 'Queue' at 0x7f3430c9d840>
    │     │      │    │                    └ 0
    │     │      │    └ <function LocalPipelineExecutor._launch_run_for_rank at 0x7f348b3f92d0>
    │     │      └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7f3430c9c6a0>
    │     └ <method 'append' of 'list' objects>
    └ []
  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/local.py", line 57, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
           │    │             │     └ 0
           │    │             └ 0
           │    └ <function PipelineExecutor._run_for_rank at 0x7f348b3f8e50>
           └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7f3430c9c6a0>
> File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/base.py", line 77, in _run_for_rank
    pipelined_data = pipeline_step(pipelined_data, rank, self.world_size)
                     │             │               │     │    └ <property object at 0x7f348b7310d0>
                     │             │               │     └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7f3430c9c6a0>
                     │             │               └ 0
                     │             └ None
                     └ 🫂 - DEDUPS: 💥 sentence-deduplication stage 2
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/base.py", line 122, in __call__
    return self.run(data, rank, world_size)
           │    │   │     │     └ 1
           │    │   │     └ 0
           │    │   └ None
           │    └ <function SentenceFindDedups.run at 0x7f34623cf1c0>
           └ 🫂 - DEDUPS: 💥 sentence-deduplication stage 2
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/dedup/sentence_dedup.py", line 163, in run
    pq = [next(sig_reader) for sig_reader in sig_readers]
                                             └ [<generator object read_sigs at 0x7f3430bff840>, <generator object read_sigs at 0x7f3430bff7d0>, <generator object read_sigs ...
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/dedup/sentence_dedup.py", line 163, in <listcomp>
    pq = [next(sig_reader) for sig_reader in sig_readers]
               │               └ <generator object read_sigs at 0x7f3430bff7d0>
               └ <generator object read_sigs at 0x7f3430bff7d0>

StopIteration
Traceback (most recent call last):
  File "/datatrove/examples/sentence_deduplication.py", line 55, in <module>
    run_example()
  File "/datatrove/examples/sentence_deduplication.py", line 50, in run_example
    print(executor_2.run())
  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/local.py", line 93, in run
    stats.append(self._launch_run_for_rank(rank, ranks_q))
  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/local.py", line 57, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/base.py", line 96, in _run_for_rank
    raise e
  File "/opt/conda/lib/python3.10/site-packages/datatrove/executor/base.py", line 77, in _run_for_rank
    pipelined_data = pipeline_step(pipelined_data, rank, self.world_size)
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/base.py", line 122, in __call__
    return self.run(data, rank, world_size)
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/dedup/sentence_dedup.py", line 163, in run
    pq = [next(sig_reader) for sig_reader in sig_readers]
  File "/opt/conda/lib/python3.10/site-packages/datatrove/pipeline/dedup/sentence_dedup.py", line 163, in <listcomp>
    pq = [next(sig_reader) for sig_reader in sig_readers]
StopIteration`
could you help me 
thanks

**Comment by guipenedo** [comment]
Hi! it seems that there are some empty signature files (`.c4_sig` files) created on step1, how many input files did you have in stage1 and how many `tasks` did you run it with? If you have more tasks than input files, then some empty sig files may be generated

**Comment by Manel-Hik** [comment]
Hi
I'm trying just with one jsonl file
number of tasks is 4 like the code in example

**Comment by guipenedo** [comment]
Try with 1 task since you only have 1 jsonl file (delete the output directory before relaunching)
