### ISSUE TITLE
Bug in url filter

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#140]
```
2024-03-29 08:17:44.786 | INFO | datatrove.executor.local:_launch_run_for_rank:73 - 1/20 tasks completed.
2024-03-29 08:17:44.788 | INFO | datatrove.executor.local:_launch_run_for_rank:73 - 2/20 tasks completed.
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/output/datatrove/src/datatrove/executor/local.py", line 68, in _launch_run_for_rank
return self._run_for_rank(rank, local_rank)
File "/output/datatrove/src/datatrove/executor/base.py", line 96, in _run_for_rank
raise e
File "/output/datatrove/src/datatrove/executor/base.py", line 83, in _run_for_rank
deque(pipelined_data, maxlen=0)
File "/output/datatrove/src/datatrove/pipeline/writers/disk_base.py", line 173, in run
for document in data:
File "/output/datatrove/src/datatrove/pipeline/extractors/base.py", line 77, in run
for doc in data:
File "/output/datatrove/src/datatrove/pipeline/filters/base_filter.py", line 50, in run
filter_result, reason = get_filter_result(self.filter(doc))
File "/output/datatrove/src/datatrove/pipeline/filters/url_filter.py", line 87, in filter
self.download_data()
File "/output/datatrove/src/datatrove/pipeline/filters/url_filter.py", line 76, in download_data
tar.extractall(download_dir)
File "/opt/conda/envs/datatrove/lib/python3.10/tarfile.py", line 2264, in extractall
self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
File "/opt/conda/envs/datatrove/lib/python3.10/tarfile.py", line 2331, in _extract_one
self._handle_fatal_error(e)
File "/opt/conda/envs/datatrove/lib/python3.10/tarfile.py", line 2327, in _extract_one
self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
File "/opt/conda/envs/datatrove/lib/python3.10/tarfile.py", line 2402, in _extract_member
os.makedirs(upperdirs)
File "/opt/conda/envs/datatrove/lib/python3.10/os.py", line 225, in makedirs
mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.cache/huggingface/assets/datatrove/filters/url_filter/adult'
"""
```

**Comment by guipenedo** [comment]
Looks like a race condition with saving the file, I think if you just rerun the pipeline it should work now

**Comment by jordane95** [comment]
This actually happens very often, like 3 in 5, especially with more workers.

**Comment by jordane95** [comment]
Plus, I wrote one custom html extractor, and find many timeout warning like this. Is there any bug?
```
2024-03-29 11:08:44.318 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:44.428 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:44.533 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:44.939 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:61 - ❌ Error "Error trying to process rule "pattern":

" while cleaning record text. Skipping record.
2024-03-29 11:08:45.043 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:45.147 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:45.256 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:45.673 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:61 - ❌ Error "Error trying to process rule "literal":

" while cleaning record text. Skipping record.
2024-03-29 11:08:45.777 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:45.884 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:45.988 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:46.403 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:61 - ❌ Error "Error trying to process rule "literal":

" while cleaning record text. Skipping record.
2024-03-29 11:08:46.511 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:46.614 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
2024-03-29 11:08:46.720 | WARNING  | datatrove.pipeline.extractors.base:timeout_extract:58 - ⏰ Timeout while cleaning record text. Skipping record.
```

**Comment by hynky1999** [comment]
@guipenedo, we could probably only download/extract on rank 0 and let others wait with some reasonable timeout ? To resolve the race condition ?

**Comment by hynky1999** [comment]
@jordane95 for the second problem, you can just increase the timeout time in constructor of your extractor.

**Comment by jordane95** [comment]
> @jordane95 for the second problem, you can just increase the timeout time in constructor of your extractor.

There are also some lines with error. Should I ignore them?

**Comment by guipenedo** [comment]
It's normal that some documents time out, they usually have malformatted html or some other issue.
The race condition thing is a bit more complex than that because in general we shouldn't assume all ranks have access to the same disk storage

**Comment by jordane95** [comment]
I'm a little confused about the timeout threshold. Is 0.1 really a good threshold for processing? It may ignore some complex html content which would introduce some bias

**Comment by jordane95** [comment]
Could you also take a look at this error? @hynky1999 @guipenedo 

```
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/output/datatrove/src/datatrove/executor/local.py", line 68, in _launch_run_for_rank
return self._run_for_rank(rank, local_rank)
File "/output/datatrove/src/datatrove/executor/base.py", line 96, in _run_for_rank
raise e
File "/output/datatrove/src/datatrove/executor/base.py", line 83, in _run_for_rank
deque(pipelined_data, maxlen=0)
File "/output/datatrove/src/datatrove/pipeline/writers/disk_base.py", line 173, in run
for document in data:
File "/output/datatrove/src/datatrove/pipeline/extractors/base.py", line 77, in run
for doc in data:
File "/output/datatrove/src/datatrove/pipeline/filters/base_filter.py", line 50, in run
filter_result, reason = get_filter_result(self.filter(doc))
File "/output/datatrove/src/datatrove/pipeline/filters/url_filter.py", line 92, in filter
url_info = self.tldextractor(url)
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/tldextract.py", line 231, in __call__
return self.extract_str(url, include_psl_private_domains, session=session)
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/tldextract.py", line 260, in extract_str
return self._extract_netloc(
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/tldextract.py", line 311, in _extract_netloc
suffix_index, is_private = self._get_tld_extractor(
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/tldextract.py", line 360, in _get_tld_extractor
public_tlds, private_tlds = get_suffix_lists(
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/suffix_list.py", line 81, in get_suffix_lists
return cache.run_and_cache(
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/tldextract/cache.py", line 208, in run_and_cache
with FileLock(lock_path, timeout=self.lock_timeout):
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/filelock/_api.py", line 297, in __enter__
self.acquire()
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/filelock/_api.py", line 264, in acquire
raise Timeout(lock_filename) # noqa: TRY301
filelock._error.Timeout: The file lock '/root/.cache/python-tldextract/3.10.13.final__datatrove__e876e6__tldextract-5.1.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock' could not be acquired.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/output/datatrove/examples/extract_cc_openwebmath_mp.py", line 92, in
main()
File "/output/datatrove/examples/extract_cc_openwebmath_mp.py", line 88, in main
executor.run()
File "/output/datatrove/src/datatrove/executor/local.py", line 112, in run
stats = list(
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/multiprocess/pool.py", line 873, in next
raise value
filelock._error.Timeout: The file lock '/root/.cache/python-tldextract/3.10.13.final__datatrove__e876e6__tldextract-5.1.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock' could not be acquired.
```

**Comment by jordane95** [comment]
> Could you try running the full pipeline with a single worker on a few (small number) of samples fist? The errors seem to be download related errors due to a large nb of concurrent tasks

Yes. Using one node with 20 cores does not throw this error. But using 60 nodes each with 20 cores will throw the previous error

**Comment by jordane95** [comment]
> Looks like a race condition with saving the file, I think if you just rerun the pipeline it should work now

May be we should run download_data during instance initialization?

**Comment by hynky1999** [comment]
> > Looks like a race condition with saving the file, I think if you just rerun the pipeline it should work now
> 
> May be we should run download_data during instance initialization?

I would rather solve this by using a lockfile.
