### ISSUE TITLE
Error when running minhash

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#157]
Have you ever seen this bug when running minhash? What might be the cause?

```
File "/output/datatrove/src/datatrove/pipeline/dedup/minhash.py", line 139, in read_sigs
File "/opt/conda/envs/datatrove/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
raise value
File "/output/datatrove/examples/minhash_deduplication_mp.py", line 157, in main
File "/output/datatrove/src/datatrove/pipeline/base.py", line 122, in __call__
Traceback (most recent call last):
File "/output/datatrove/src/datatrove/executor/base.py", line 77, in _run_for_rank
"""
File "/output/datatrove/src/datatrove/pipeline/dedup/minhash.py", line 378, in run
AssertionError: Hash order error. f.tell()=13504008, min_hash=167858917, sigdata=(62530469, 17634173, 42943397, 32616677, 9946320, 97645252, 33852496, 40487027, 13335797, 46577224, 99341049, 65232832, 98314078), last=(168841106, 1007538214, 22584412, 260559064, 494471935, 336374100, 632602342, 773108968, 87337671, 1064337302, 10811556, 112410251, 404805684)
File "/output/datatrove/src/datatrove/executor/local.py", line 112, in run
stats = list(
The above exception was the direct cause of the following exception:
```

**Comment by akshayg08** [comment]
I am facing the same issue, @jordane95 did you find the reason for this?

**Comment by jordane95** [comment]
> I am facing the same issue, @jordane95 did you find the reason for this?

Could you try to delete the log and rerun the job? I suppose that one hash was compute/stored incorrectly due to machine corruption.

**Comment by akshayg08** [comment]
I deleted the log and rerun 2 times. I looked at the signatures too, none of the signatures look 0 to me. But the error in stage 2 shows that the min_hash is 0.

**Comment by Maghoumi** [comment]
I'm also running into a similar issue, when running with a large number of workers. What exactly could be the cause of this error?

The code in `minhash.py` seems to be relying on a bool flag `ensure_order` (`True` by default). I wonder what the implications of setting `ensure_order=False` would be.

**Comment by Maghoumi** [comment]
Tagging @guipenedo since git blame shows him as the contributor to this function in #82.

Long story short, we are trying to run minhash deduplication on some large scale datasets (4TB and 8TB) and we are sporadically running into this error. For the 8TB dataset, we are consistently seeing this error at the bucketization stage:

```
0:     ensure_order is False or last is None or sigdata >= last
0: AssertionError: Hash order error. f.tell()=280, min_hash=644059, sigdata=(575424, 9907098, 11660665, 16233260, 21845025, 4116939, 677894, 25918161, 26999693, 1259831, 7481797, 3715207, 24229330), last=(779927, 2757959, 9287481, 6215803, 3588275, 4152628, 452551, 26101124, 5808549, 4675425, 17486690, 5048257, 9197709)
```

Our pipeline setup is fairly straightforward:

**Stage 1 setup:**
```
minhash_config = MinhashConfig(
    num_buckets=20,
    hashes_per_bucket=13,
    hash_config=HashConfig(precision=32),
)
    stage1 = SlurmPipelineExecutor(
        job_name=f"{EXPERIMENT_NAME}-dedup-stage-1",
        pipeline=[
            JsonlReader(INPUT_DATASET_PATH, text_key=INPUT_DATASET_KEY),
            MinhashDedupSignature(output_folder=STAGE_1_OUTPUT, config=minhash_config),
        ],
        tasks=NUM_TASKS_STAGE_1_COMPUTE_MINHASH,
        time="16:00:00",
        partition=PARTITION,
        logging_dir=STAGE_1_LOGS,
        slurm_logs_folder=f"{STAGE_1_LOGS}/slurm_logs",
        cpus_per_task=1,
        mem_per_cpu_gb=MEM_GB_STAGE_1_COMPUTE_MINHASH,
        max_array_launch_parallel=True,
        env_command=env_command
    )
    stage1.run()
```

**Stage 2 setup:**
```
    stage2 = SlurmPipelineExecutor(
        job_name=f"{EXPERIMENT_NAME}-dedup-stage-2",
        pipeline=[
            MinhashDedupBuckets(
                input_folder=STAGE_1_OUTPUT,
                output_folder=STAGE_2_OUTPUT,
                config=minhash_config,
            ),
        ],
        tasks=NUM_TASKS_STAGE_2_BUCKETIZE,
        time="16:00:00",
        partition=PARTITION,
        logging_dir=STAGE_2_LOGS,
        slurm_logs_folder=f"{STAGE_2_LOGS}/slurm_logs",
        cpus_per_task=1,
        mem_per_cpu_gb=MEM_GB_STAGE_2_BUCKETIZE,
        max_array_launch_parallel=True,
        env_command=env_command,
    )
    stage2.run()
```

Any pointers would be greatly appreciated.

**Comment by guipenedo** [comment]
Hi, 
The first step (MinhashDedupSignature) will create files with sequences of `hashes_per_bucket` integers followed by the document id. These files will then be sorted, so that when we read from multiple files in the bucketing step, we can do a single pass through each file, by pulling the top element from each one and adding it to a priority queue. If these files are not sorted, then the single pass method will not work and you have the risk of missing multiple duplicates. 

Typically this (the file not being sorted) happens when there was some network issue/corruption when sorting and saving the files. You absolutely do not want to turn `ensure_order` to False, as then you would be silently missing a lot of duplicates. The only solution here is to rerun the first step for the tasks that produced the corrupted/unordered files. 

You can add `file_stem` to the assert error message so that you know which rank from step1 failed. Then you can delete that rank's completion file and rerun step1 (only the ranks you removed should run). I will consider adding a verification at the end of step1 to make sure the file is sorted before the task completes, so that this issue is caught directly during step1.

**Comment by Maghoumi** [comment]
Thanks for your prompt response, I will try your suggestions.

**Comment by Maghoumi** [comment]
A quick update on this issue:

After adding the `file_stem` value to the log, and attempting to re-run, we noticed that some files from stage 1 were indeed corrupt. This turned out to be caused by the worker running out of disk storage space :man_facepalming: 
Those ranks had silently failed, which is why we didn't catch the issue after stage 1 finished.

After increasing the disk space and re-running stage 1, we stopped seeing the error at stage 2.

Thanks again for your help Guilherme!

**Comment by guipenedo** [comment]
Glad it's working now! Just to clarify, were the ranks that had failed marked as completed (did they have a file in `completions`)?

**Comment by Maghoumi** [comment]
Sorry I'm not sure. I cleared out all the results before retrying a second time.
