### ISSUE TITLE
`HuggingFaceDatasetReader` Expects Missing Attribute `split`

### ISSUE THREAD

**Issue by axelmagn** [huggingface/datatrove#233]
In trying to build pipelines that source from the wikipedia dataset on hugging face, the reader seems to expect a `split` attribute that is not present for the dataset:

```
AttributeError: 'DatasetDict' object has no attribute 'shard'. Did you mean: 'shape'?
```

I think that this might be due to the various forms HF datasets can take.  It's unclear whether the fix needs to be on the datasets side or the datatrove side, but I am posting this issue here since it is at least superficially a datatrove error. Nonetheless, it's blocking me, and any advice on workarounds or fixes are much appreciated.

If folks know the fix but don't have the time, I am willing to have a a crack at drafting a pull request.

Repro code:

```
from datatrove.executor import LocalPipelineExecutor
from datatrove.pipeline.readers import HuggingFaceDatasetReader
from datatrove.pipeline.writers import ParquetWriter

LocalPipelineExecutor(
    pipeline=[
        HuggingFaceDatasetReader(
            "wikimedia/wikipedia", dataset_options={"name": "20231101.ab"}, limit=128
        ),
        ParquetWriter(output_folder="/tmp/repro"),
    ]
).run()
```

Dependencies (installed via poetry):

```
python = "^3.10"
datatrove = { extras = ["io", "processing", "s3"], version = "^0.2.0" }
gin-config = "^0.5.0"
click = "^8.1.7"
mwparserfromhell = "^0.6.6"
datasets = "2.18.0" # added thinking that maybe I needed to downgrade
```

Full trace:

```
Traceback (most recent call last):
  File "/Users/axelmagn/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/axelmagn/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/nlp_curator_datatrove/wikipedia/repro1.py", line 12, in <module>
    ).run()
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/local.py", line 125, in run
    stats.append(self._launch_run_for_rank(rank, ranks_q))
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/local.py", line 74, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/base.py", line 96, in _run_for_rank
    raise e
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/base.py", line 83, in _run_for_rank
    deque(pipelined_data, maxlen=0)
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/pipeline/writers/disk_base.py", line 173, in run
    for document in data:
  File "/Users/axelmagn/Workspace/Writer/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/pipeline/readers/huggingface.py", line 61, in run
    shard = ds.shard(world_size, rank, contiguous=True)
AttributeError: 'DatasetDict' object has no attribute 'shard'. Did you mean: 'shape'?
```

**Comment by hynky1999** [comment]
Hey Axel,
it's seems to does have a split. Can you try specifying "train" as a split ?

**Comment by axelmagn** [comment]
Yep!  That was what I was missing.  Bit of a facepalm moment.  Thanks for the help.
