### ISSUE TITLE
SlurmExecutor error: `TypeError: cannot pickle 'module' object`

### ISSUE THREAD

**Issue by axelmagn** [huggingface/datatrove#236]
I am writing a simple ingestion pipeline for a hugging face dataset that is intended for execution on Slurm.  However, when running at scale, the slurm executor seems to fail to pickle itself in `datatrove/executor/slurm.py:236`.

Any thoughts on what could be the issue?

Full traceback:

```
Traceback (most recent call last):                                                                                                                                            
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                                  
    return _run_code(code, main_globals, None,                                                                                                                                
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/runpy.py", line 86, in _run_code                                                             
    exec(code, run_globals)                                                                                                                                                   
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/nlp_curator_datatrove/wikipedia/ingest.py", line 56, in <module>                        
    run()                                                                                                                                                                     
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__               
    return self.main(*args, **kwargs)                                                                                                                                         
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main                   
    rv = self.invoke(ctx)                                                                                                                                                     
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke                 
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                            
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke                  
    return __callback(*args, **kwargs)                                                                                                                                        
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/nlp_curator_datatrove/wikipedia/ingest.py", line 23, in run                             
    make_executor().run()                                                                                                                                                     
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/slurm.py", line 177, in run       
    self.launch_job()                                                                                                                                                         
  File "/fsx/axel/workspace/nlp.curator/nlp.curator.datatrove/.venv/lib/python3.10/site-packages/datatrove/executor/slurm.py", line 236, in launch_job
    executor = deepcopy(self)                                                                                                                                                 
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 172, in deepcopy                                                              
    y = _reconstruct(x, memo, *rv)                                                                                                                                            
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 271, in _reconstruct                                                          
    state = deepcopy(state, memo)                                                                                                                                             
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 146, in deepcopy                                                              
    y = copier(x, memo)                                                                                                                               
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 231, in _deepcopy_dict                                                        
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                                            
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 146, in deepcopy                                                              
    y = copier(x, memo)                                                                                                                               
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 206, in _deepcopy_list                                                        
    append(deepcopy(a, memo))                                                                                                                         
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 172, in deepcopy                                                              
    y = _reconstruct(x, memo, *rv)                                                                                                                                            
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 271, in _reconstruct                                                          
    state = deepcopy(state, memo)                                                                                                                                             
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 146, in deepcopy                                                                                                    
    y = copier(x, memo)                                                                                                                               
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 231, in _deepcopy_dict                                                        
    y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                                            
  File "/fsx/axel/.pyenv/versions/3.10.14/lib/python3.10/copy.py", line 161, in deepcopy                                                              
    rv = reductor(4)                                                                                                                                                          
TypeError: cannot pickle 'module' object
```

The pipeline in question:

```
[
        HuggingFaceDatasetReader(
            dataset_id, # wikimedia/wikipedia
            dataset_options={"name": "20231101.en", "split": "train"},
            limit=limit,
        ),
        ConvertToExtendedDoc(), # custom
        CopyTextToRaw(), # custom
        MediaWikiParser(), # custom
        ParquetWriter(output_folder=output_dir),
    ]
```

And the slurm executor config (configured via gin):

```
SlurmPipelineExecutor.job_name="wikipedia_ingest"
SlurmPipelineExecutor.tasks=1024
SlurmPipelineExecutor.time="48:00:00"
SlurmPipelineExecutor.randomize_start=True
SlurmPipelineExecutor.mem_per_cpu_gb=2
SlurmPipelineExecutor.partition="dev"
SlurmPipelineExecutor.logging_dir=@log_path()
SlurmPipelineExecutor.slurm_logs_folder=@local/log_path()
```

**Comment by axelmagn** [comment]
I found the issue in my own code (see `MediaWikiParser` in `repro1.py`).  No clue why I wrote it that way.  Issue resolved.  For others: don't use modules as attributes if you want to pickle something.

**Comment by guipenedo** [comment]
I had planned to take out some time this week to investigate, glad you figured it out :)
